presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: op1st/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/pre-commit:v0.17.0
          command:
            - "prow-job-precommit"
  - name: peribolos
    decorate: true
    run_if_changed: peribolos.yaml
    skip_report: false
    context: op1st/prow/peribolos
    spec:
      containers:
        - image: gcr.io/k8s-prow/peribolos:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -ex
              /ko-app/peribolos --config-path peribolos.yaml --github-token-path /etc/github/oauth \
                --min-admins=2 \
                --maximum-removal-delta=0.15 \
                --require-self=true \
                --fix-org \
                --fix-org-members \
                --fix-repos \
                --fix-teams \
                --fix-team-members \
                --fix-team-repos \
                --allow-repo-archival \
          volumeMounts:
            - name: github-oauth
              mountPath: /etc/github
      volumes:
        - name: github-oauth
          secret:
            secretName: github-oauth

postsubmits:
  - name: peribolos
    decorate: true
    run_if_changed: peribolos.yaml
    skip_report: false
    context: op1st/prow/peribolos
    branches:
      - ^main$
    spec:
      containers:
        - image: gcr.io/k8s-prow/peribolos:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -ex
              /ko-app/peribolos --config-path config.yaml --github-token-path /etc/github/oauth \
                --min-admins=2 \
                --maximum-removal-delta=0.15 \
                --require-self=true \
                --fix-org \
                --fix-org-members \
                --fix-repos \
                --fix-teams \
                --fix-team-members \
                --fix-team-repos \
                --allow-repo-archival \
                --confirm
          volumeMounts:
            - name: github-oauth
              mountPath: /etc/github
      volumes:
        - name: github-oauth
          secret:
            secretName: github-oauth
